### ISSUE TITLE
update jackson

### ISSUE THREAD

**Issue by eroux** [helun/Ektorp#268]
I recently bumped into [this bug](https://github.com/FasterXML/jackson-databind/issues/1101) in [a project](https://github.com/BuddhistDigitalResourceCenter/auth-api) and had to exclude jackson dependency of ektorp because it's too old. Please update jackson version.

**Comment by YannRobert** [comment]
Did you try to use ```<dependencyManagement/>``` in maven pom.xml in order to use the version you like?

**Comment by eroux** [comment]
That's a good idea, I just used the `<exclusion>` mechanism actually...

**Comment by huxi** [comment]
Latest jackson 2.9.0 is causing the following exception with current ektorp 1.4.4:

```
Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.SerializationConfig.withSerializationInclusion(Lcom/fasterxml/jackson/annotation/JsonInclude$Include;)Lcom/fasterxml/jackson/databind/SerializationConfig;
	at org.ektorp.impl.StdObjectMapperFactory.applyDefaultConfiguration(StdObjectMapperFactory.java:50)
	at org.ektorp.impl.StdObjectMapperFactory.createObjectMapper(StdObjectMapperFactory.java:26)
	at org.ektorp.impl.StdCouchDbInstance.<init>(StdCouchDbInstance.java:40)
	at org.ektorp.impl.StdCouchDbInstance.<init>(StdCouchDbInstance.java:32)
```

cc @cowtowncoder

**Comment by cowtowncoder** [comment]
@huxi This method was deprecated in 2.7, replaced with `withPropertyInclusion()`. In hindsight might have been better to wait for one more version (since next will very likely be breaking, 3.0).
But as it is, this needs to be updated.

**Comment by YannRobert** [comment]
@huxi thank you for the report, could you please fill a separate issue for this ? In the time it takes to change this, you can always write and inject your own class implementing the interface.

**Comment by YannRobert** [comment]
Please see PR #273
I bumped the dependency to the latest version of Jackson lib that does not break any test.

There is a feature in Ektorp (```@DocumentReference```) that does not work with Jackson 2.7.0 or later.
If you do not use this feature (I guess it is not widely used), you can upgrade Jackson to a later version in your own application.

**Comment by huxi** [comment]
Thanks a lot for this fix and the release of 1.5.0!

Small problem: the release and related changes aren't mentioned in [changelog.md](https://github.com/helun/Ektorp/blob/master/changelog.md).
